export interface userObject {
  id: string | null | undefined;
  orgId: string | null | undefined;
  campusId: string | null | undefined;
  type: string;
  banner: string;
  image: string;
  profileImage: string;
  title: string | null;
  name: string | null | undefined;
  description: string | null;
  contact: string | null | undefined;
  email: string | null | undefined;
  mobile: string | null | undefined;
  city: string | null | undefined;
  country: string | null | undefined;
  created_date: string | null | undefined;
  updated_date: string | null | undefined;
  enabled: boolean;
  verified: boolean;
  blocked: boolean;
  appState: string | null | undefined;
  aggregateVerifier: string | null | undefined;
  typeOfLogin: string | null | undefined;
  verifier: string | null | undefined;
  verifierId: string | null | undefined;
  dappShare: string | null | undefined;
  oAuthIdToken: string | number | null;
  oAuthAccessToken: string | number | null;
  idToken: string | number | null;
  isMfaEnabled: boolean;
}
